### ISSUE TITLE
CRSF Feature Creep

### ISSUE THREAD

**Issue by gke** [CapnBry/CRServoF#10]
Bryan,

Good job on the adapter. Nice clean code.

Betaflight/CrossBow seem to have feature creep with CRSF. Do you know whether CRSF_FRAMETYPE_RC_CHANNELS_PACKED and CRSF_FRAMETYPE_LINK_STATISTICS packet types will remain the baseline for ExpressLRS.  Some of us write our own flight control code and tracking moving specs does not thrill me.  Apologies for the cross post on ExpressLRS..

Thanks
Greg

**Comment by CapnBry** [comment]
CRSF_FRAMETYPE_RC_CHANNELS_PACKED and CRSF_FRAMETYPE_LINK_STATISTICS are CRSF packet types that are fundamental to the CRSF protocol and have been around for several years, they will not be changing any time soon.

Unless you count CRSFv3, which we will be supporting and changes these packet types, but I am sure these will be around for a while until everyone supports that.
