### ISSUE TITLE
Adapting to Pro Micro without "#include <functional>"

### ISSUE THREAD

**Issue by robhaswell** [CapnBry/CRServoF#25]
I'm trying to adapt CRSFJoystick, and so also this library, to run on a SparkFun Pro Micro. The error I am running into is:

```
CrsfSerial/CrsfSerial.h:4:10: fatal error: functional: No such file or directory
```

This means that I can't use the `std::function` syntax to declare the event handlers.

My software experience is primarily Python so I am struggling with the deep magic here, would you be able to help me get this compiled for my platform please? I don't really know what I am doing but I think I have worked out that the SparkFun board for the Arduino IDE doesn't have a new enough C compiler. Do you think that using platformio might be able to make a difference?

**Comment by CapnBry** [comment]
I removed `<functional>` back in May, man. Catch up! :-D

**Comment by robhaswell** [comment]
Lol I literally just now discovered this and was about to close this issue! Thanks for getting back to me.
