### ISSUE TITLE
CRSF frame sanity check incorrect.

### ISSUE THREAD

**Issue by hydra** [CapnBry/CRServoF#28]
From the TBS spec, "Frame Length: ... Valid range is between 2 and 62 ...".

But:

https://github.com/CapnBry/CRServoF/blob/d5e739f20167f8594e2cf4cbc8937b05946c1787/lib/CrsfSerial/CrsfSerial.cpp#L86

and:

https://github.com/CapnBry/CRServoF/blob/d5e739f20167f8594e2cf4cbc8937b05946c1787/lib/CrsfSerial/crsf_protocol.h#L15

CRSF 'FrameLength' field != CRSF BUFFER SIZE / `CRSF_MAX_PACKET_LEN`.

**Comment by CapnBry** [comment]
🤣 It is so ambiguous everywhere what the max was, especially when I wrote this and had a lot less experience with everyone's implementation (which is the only spec I know). I've updated the code to clarify. I didn't know if the original define (64) was supposed to represent:
* The max total packet size. The size of the buffer need to hold an entire CRSF packet including the start byte, len, type, payload and CRC. The payload data is limited to 60 bytes. **TRUE**
* The max total size of everything following the length. FALSE
* The max total size of the payload portion, including TYPE, excluding the CRC. FALSE
* The max total size of the data portion of the payload, excluding the TYPE and CRC. FALSE
