### ISSUE TITLE
Servo.h and Servo.cpp

### ISSUE THREAD

**Issue by sk8board** [CapnBry/CRServoF#35]
Hello Bryan,

I notice the code for a Pico will not compile. There are errors for undefined variables, some of which require Servo.h and Servo.cpp files, but these files are not included in the library.

Are the Servo.h and Servo.cpp files standard files that can be pulled from another source? Do you know where you were planning to get the Servo.h and Servo.cpp files?

**Comment by CapnBry** [comment]
The Pico support is not done and I have no plans for when it will be. The target in platformio.ini snuck in by mistake when working on something else.
