### ISSUE TITLE
Use STM32 as a receiver.

### ISSUE THREAD

**Issue by fbdfbd3371** [CapnBry/CRServoF#40]
Hello! I have a reverse question. I have a flight controller and I need to transmit control signals to it from STM32 via UART. I realized that CRSF is good for this task. Please tell me, is it possible to emulate a receiver (for example, ExpressLRS) on STM32? Thank you!

**Comment by sk8board** [comment]
Maybe I do not understand your question, but I think if you read the content on this repository home page and watch the video, then I believe you will understand the scope of this work.

Did you read this webpage and watch the video?

https://github.com/CapnBry/CRServoF

**Comment by CapnBry** [comment]
https://github.com/crsf-wg/crsf/wiki
