### ISSUE TITLE
Remapping PWM outputs

### ISSUE THREAD

**Issue by voxpopulous** [CapnBry/CRServoF#41]
Can we remap PWM outputs in code, for them to be in order, for example form b12 to a11 on bluepill?

**Comment by CapnBry** [comment]
https://github.com/CapnBry/CRServoF/blob/main/include/target.h#L8

**Comment by voxpopulous** [comment]
> https://github.com/CapnBry/CRServoF/blob/main/include/target.h#L8

Yeah, i've seen that. So i can remap them as i wish?

**Comment by CapnBry** [comment]
The pins must be hardware capable of PWM, so sort of. There could be other limitations and interactions with how the Arduino platform is using pins as well (such as for the serial connections etc). I'd recommend you experiment with it. Why are you even asking the question if you knew you could just edit that file? 😆 Were you worried that putting in something wrong could launch nuclear missiles? I assure you that will not happen.
