### ISSUE TITLE
Add telemetry support for sensors

### ISSUE THREAD

**Issue by neuhausj** [CapnBry/CRServoF#7]
Hello,
I really like this project and would like to know if it is possible to add telemetry support, in order to send either digital or analog signals back to the transmitter.
There could be a lot of use: voltage or current sensor, barometer, GPS...
Thanks for your support,

**Comment by CapnBry** [comment]
There already is telemetry support for VBAT, but I will not be implementing other protocols to connect more external sensor devices. I'd recommend looking into a flight controller, which has servo outputs and support tons of sensors right out of the box without having to Frankenstein things together.

**Comment by neuhausj** [comment]
Hello,
Thanks for the quick answer.
True for the FC, but I will be lose the servo pins.
I will try to take a look at the Vbat implementation and adapt it to the barometer.
